services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - ./data:/app/data
    environment:
      ALLOW_SIGNUP: "false"
      DEFAULT_GROUP: Home
      DEFAULT_HOUSEHOLD: Home
      TZ: ${TZ}
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "1000:1000"
    read_only: true
    tmpfs:
      - /tmp
      - /run
    networks:
      - frontend-net
      - backend-net
networks:
  frontend-net:
    internal: false
  backend-net:
    internal: true