services:
  actual:
    image: actualbudget/actual-server:latest
    container_name: actual
    restart: unless-stopped
    ports:
      - "127.0.0.1:5006:5006"
    volumes:
      - ./server-files:/data
    environment:
      ACTUAL_OPENID_DISCOVERY_URL: ${ACTUAL_OPENID_DISCOVERY_URL:-}
      ACTUAL_OPENID_CLIENT_ID: ${ACTUAL_OPENID_CLIENT_ID:-}
      ACTUAL_OPENID_CLIENT_SECRET: ${ACTUAL_OPENID_CLIENT_SECRET:-}
      ACTUAL_OPENID_SERVER_HOSTNAME: ${ACTUAL_OPENID_SERVER_HOSTNAME:-}
      ACTUAL_OPENID_AUTH_METHOD: ${ACTUAL_OPENID_AUTH_METHOD:-openid}
      ACTUAL_LOGIN_METHOD: ${ACTUAL_LOGIN_METHOD:-password}
      ACTUAL_ALLOWED_LOGIN_METHODS: ${ACTUAL_ALLOWED_LOGIN_METHODS:-password}
      ACTUAL_OPENID_ENFORCE: ${ACTUAL_OPENID_ENFORCE:-false}
      ACTUAL_USER_CREATION_MODE: ${ACTUAL_USER_CREATION_MODE:-manual}
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "1000:1000"
    networks:
      - frontend-net
      - backend-net
networks:
  frontend-net:
    external: true
    name: homelab_frontend
  backend-net:
    external: true
    name: homelab_backend
