name: vaultwarden
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    env_file:
      - .env
    environment:
      ROCKET_PORT: "80"
    volumes:
      - ./data:/data
    ports:
      - "127.0.0.1:8081:80"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "1000:1000"
    read_only: true
    tmpfs:
      - /tmp
      - /run
    networks:
      - frontend-net
      - backend-net
networks:
  frontend-net:
    external: true
    name: homelab_frontend
  backend-net:
    external: true
    name: homelab_backend
