name: puppygraph
services:
  puppygraph:
    image: puppygraph/puppygraph:latest
    container_name: puppygraph
    environment:
      - PUPPYGRAPH_USERNAME=${PUPPYGRAPH_USERNAME}
      - PUPPYGRAPH_PASSWORD=${PUPPYGRAPH_PASSWORD}
      - QUERY_TIMEOUT=5m
    ports:
      - "127.0.0.1:8082:8081"
      - "127.0.0.1:8182:8182"
      - "127.0.0.1:7687:7687"
    volumes:
      - ./data:/data
    restart: unless-stopped