- Homelab:
    - GitHub Repository:
        - abbr: GH
          href: https://github.com/dcazes/homelab
    - Documentation:
        - abbr: Docs
          href: https://github.com/dcazes/homelab/wiki
    - Issue Tracker:
        - abbr: Issues
          href: https://github.com/dcazes/homelab/issues
    - Releases:
        - abbr: Releases
          href: https://github.com/dcazes/homelab/releases
- Network:
    - Tailscale Admin:
        - abbr: TS
          href: https://login.tailscale.com/admin/machines
    - Router Admin:
        - abbr: Router
          href: http://192.168.1.1
    - Pi-hole:
        - abbr: Pi-hole
          href: http://pi.hole/admin
- Tools:
    - Speed Test:
        - abbr: Speed
          href: https://speedtest.net
    - Ping Test:
        - abbr: Ping
          href: https://www.ping.eu/
    - Port Checker:
        - abbr: Port
          href: https://www.yougetsignal.com/tools/open-ports/