- Homelab:
    - GitHub - homelab:
        - abbr: GH
          href: https://github.com/dcazes/homelab
    - Tailscale admin:
        - abbr: TS
          href: https://login.tailscale.com/admin/machines
