- resources:
    - cpu:
        label: CPU Usage
    - memory:
        label: Memory Usage
    - disk:
        label: Disk Usage
        path: /
    - uptime:
        label: System Uptime
- information:
    - github:
        user: dcazes
        repo: homelab
        type: stars
    - rss:
        url: https://feeds.feedburner.com/techcrunch/IT
        title: TechCrunch
        limit: 3
- search:
    provider: duckduckgo
    target: _blank
